#ORIGIN
LIFERAY_MARKETPLACE_ORIGIN_OAUTH_CLIENT_ID=
LIFERAY_MARKETPLACE_ORIGIN_OAUTH_CLIENT_SECRET=
LIFERAY_MARKETPLACE_ORIGIN_URL=
LIFERAY_MARKETPLACE_ORIGIN_MARKETPLACE_SITE_GROUP_ID=
LIFERAY_MARKETPLACE_ORIGIN_GLOBAL_SITE_GROUP_ID=
LIFERAY_MARKETPLACE_ORIGIN_BUNDLED_CATEGORY_ID=
LIFERAY_MARKETPLACE_ORIGIN_FREE_CATEGORY_ID=
LIFERAY_MARKETPLACE_ORIGIN_PAID_CATEGORY_ID=
LIFERAY_MARKETPLACE_ORIGIN_SOLUTION_CATEGORY_ID=

#DESTINATION
LIFERAY_MARKETPLACE_DESTINATION_OAUTH_CLIENT_ID=
LIFERAY_MARKETPLACE_DESTINATION_OAUTH_CLIENT_SECRET=
LIFERAY_MARKETPLACE_DESTINATION_URL=
LIFERAY_MARKETPLACE_DESTINATION_MARKETPLACE_SITE_GROUP_ID=
LIFERAY_MARKETPLACE_DESTINATION_GLOBAL_SITE_GROUP_ID=